version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: wechaty
    versions:
    - 0.7.dev17
  - dependency-name: wechaty-puppet-service
    versions:
    - 0.7.dev2
